"use client";

import { useEffect, useId, useState } from "react";

/**
 * TinyLogo — the brand mark (the meta-agent: a breathing neon core with
 * tinys orbiting it), inlined so it re-colors LIVE. Same geometry as
 * public/logo.svg (generated by scripts/gen-logo.mjs), but every fill is
 * derived from --tiny-accent via color-mix, so the logo follows the theme
 * the instant it changes — set_theme (the agent), preset picker, per-tiny
 * accents: the mark is never a stale green when the room is purple.
 *
 * Pass `accent` to pin a color regardless of theme (e.g. previews).
 */
export default function TinyLogo({
  size = 24,
  accent,
  className,
}: {
  size?: number;
  /** hex override; default follows var(--tiny-accent) live */
  accent?: string;
  className?: string;
}) {
  const id = useId().replace(/[^a-zA-Z0-9]/g, "");
  // SMIL can't be gated by CSS media queries, so the <animate> nodes are
  // rendered only after mount and only when motion is allowed — SSR and
  // prefers-reduced-motion both get the identical static rest frame.
  const [animate, setAnimate] = useState(false);
  useEffect(() => {
    if (!window.matchMedia("(prefers-reduced-motion: reduce)").matches) setAnimate(true);
  }, []);

  const a = accent ?? "var(--tiny-accent)";
  const highlight = `color-mix(in srgb, ${a} 8%, white)`;
  const shade = `color-mix(in srgb, ${a} 70%, black)`;
  const lightDot = `color-mix(in srgb, ${a} 51%, white)`;

  return (
    <svg
      viewBox="0 0 120 120"
      width={size}
      height={size}
      className={className}
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        <radialGradient id={`${id}-glow`} cx="50%" cy="50%" r="50%">
          <stop offset="0%" style={{ stopColor: a }} stopOpacity="0.85" />
          <stop offset="55%" style={{ stopColor: a }} stopOpacity="0.22" />
          <stop offset="100%" style={{ stopColor: a }} stopOpacity="0" />
        </radialGradient>
        <radialGradient id={`${id}-core`} cx="50%" cy="45%" r="55%">
          <stop offset="0%" style={{ stopColor: highlight }} />
          <stop offset="45%" style={{ stopColor: a }} />
          <stop offset="100%" style={{ stopColor: shade }} />
        </radialGradient>
      </defs>
      {/* no background rect: the mark sits on the page's own bg */}
      <circle cx="60" cy="60" r="34" fill={`url(#${id}-glow)`}>
        {animate && (
          <>
            <animate attributeName="r" values="30;38;30" dur="4s" repeatCount="indefinite" />
            <animate attributeName="opacity" values="0.7;1;0.7" dur="4s" repeatCount="indefinite" />
          </>
        )}
      </circle>
      <g>
        {animate && (
          <animateTransform attributeName="transform" type="rotate" from="0 60 60" to="360 60 60" dur="14s" repeatCount="indefinite" />
        )}
        <circle cx="60" cy="18" r="4" style={{ fill: a }} />
        <circle cx="102" cy="60" r="3" style={{ fill: a }} opacity="0.8" />
        <circle cx="60" cy="102" r="3.4" style={{ fill: lightDot }} />
      </g>
      <g>
        {animate && (
          <animateTransform attributeName="transform" type="rotate" from="360 60 60" to="0 60 60" dur="20s" repeatCount="indefinite" />
        )}
        <circle cx="24" cy="44" r="2.6" style={{ fill: a }} opacity="0.7" />
        <circle cx="96" cy="88" r="2.6" style={{ fill: a }} opacity="0.7" />
      </g>
      <circle cx="60" cy="60" r="15" fill={`url(#${id}-core)`}>
        {animate && <animate attributeName="r" values="14;16;14" dur="4s" repeatCount="indefinite" />}
      </circle>
    </svg>
  );
}
