#!/usr/bin/env node
/**
 * gen-logo.mjs — single source of truth for the tiny brand mark.
 *
 * The mark ("the meta-agent": a breathing neon core with tinys orbiting it)
 * is derived ENTIRELY from one accent hex — highlight, shade, light orbit
 * dot and the near-black background are fixed white/black mixes of it, so
 * the same geometry re-renders in any accent. This is what lets the agent
 * re-color the logo: change the accent, regenerate (or, on web, just move
 * the CSS var — components/TinyLogo.tsx renders the same geometry live).
 *
 *   node scripts/gen-logo.mjs            # brand green #00FF88
 *   node scripts/gen-logo.mjs "#bd93f9"  # any accent
 *
 * Emits (requires rsvg-convert on PATH for the PNGs):
 *   public/logo.svg                       animated, rounded (share/docs)
 *   public/icon-source.svg                static, opaque square (icon source)
 *   public/icon-192.png / icon-512.png / icon-maskable-512.png
 *   app/icon.png                          Next.js convention favicon (512)
 *   ios/Tiny/Assets.xcassets/AppIcon.appiconset/AppIcon-1024{,-dark,-tinted}.png
 *   ios/TinyWatch/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png
 *   android/{app,wear}/src/main/res/drawable/ic_launcher_foreground.xml
 */
import { execFileSync } from 'node:child_process'
import { writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

// ── palette derivation ──────────────────────────────────────────────────────
const hexToRgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16))
const rgbToHex = (c) => '#' + c.map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, '0')).join('')
const mixWhite = (c, t) => c.map((v) => v + (255 - v) * t)
const scale = (c, t) => c.map((v) => v * t)

export function derivePalette(accentHex) {
  if (!/^#[0-9a-fA-F]{6}$/.test(accentHex)) throw new Error(`bad accent hex: ${accentHex}`)
  const a = hexToRgb(accentHex)
  return {
    accent: accentHex,                            // core mid, orbit dots
    highlight: rgbToHex(mixWhite(a, 0.92)),       // core hot center  (#00FF88 → #eafff4)
    shade: rgbToHex(scale(a, 0.706)),             // core rim         (#00FF88 → #00b460)
    lightDot: rgbToHex(mixWhite(a, 0.49)),        // bright orbit dot (#00FF88 → #7dffc3)
    bg: rgbToHex(a.map((v) => 2 + v * 0.0155)),   // near-black tint  (#00FF88 → #020604)
  }
}

// ── geometry (viewBox 0 0 120 120, center 60) ───────────────────────────────
// halo r34 breathing · two counter-rotating orbit groups · core r15.
// Outermost reach: dot at (60,18) r4 → 46 from center = 38% of width, inside
// the 40% maskable safe zone, so one render serves squircle + circle masks.

const defs = (p, id) => `  <defs>
    <radialGradient id="${id}-glow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="${p.accent}" stop-opacity="0.85"/>
      <stop offset="55%" stop-color="${p.accent}" stop-opacity="0.22"/>
      <stop offset="100%" stop-color="${p.accent}" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="${id}-core" cx="50%" cy="45%" r="55%">
      <stop offset="0%" stop-color="${p.highlight}"/>
      <stop offset="45%" stop-color="${p.accent}"/>
      <stop offset="100%" stop-color="${p.shade}"/>
    </radialGradient>
  </defs>`

const orbitDots = (p) => `    <circle cx="60" cy="18" r="4" fill="${p.accent}"/>
    <circle cx="102" cy="60" r="3" fill="${p.accent}" opacity="0.8"/>
    <circle cx="60" cy="102" r="3.4" fill="${p.lightDot}"/>`

const counterDots = (p) => `    <circle cx="24" cy="44" r="2.6" fill="${p.accent}" opacity="0.7"/>
    <circle cx="96" cy="88" r="2.6" fill="${p.accent}" opacity="0.7"/>`

/** Animated mark — the gist original, palette-parameterized. */
export function animatedSvg(p) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" role="img" aria-label="tiny">
  <!-- tiny — the meta-agent. A living neon node with tinys orbiting it (the Universe).
       GENERATED by scripts/gen-logo.mjs — edit the template there, not this file. -->
${defs(p, 't')}
  <rect width="120" height="120" rx="26" fill="${p.bg}"/>
  <circle cx="60" cy="60" r="34" fill="url(#t-glow)">
    <animate attributeName="r" values="30;38;30" dur="4s" repeatCount="indefinite"/>
    <animate attributeName="opacity" values="0.7;1;0.7" dur="4s" repeatCount="indefinite"/>
  </circle>
  <g>
    <animateTransform attributeName="transform" type="rotate" from="0 60 60" to="360 60 60" dur="14s" repeatCount="indefinite"/>
${orbitDots(p)}
  </g>
  <g>
    <animateTransform attributeName="transform" type="rotate" from="360 60 60" to="0 60 60" dur="20s" repeatCount="indefinite"/>
${counterDots(p)}
  </g>
  <circle cx="60" cy="60" r="15" fill="url(#t-core)">
    <animate attributeName="r" values="14;16;14" dur="4s" repeatCount="indefinite"/>
  </circle>
</svg>
`
}

/** Static, opaque, full-bleed square — the icon source (iOS masks its own
 *  squircle; maskable PWA icons mask a circle; both need alpha-free bleed). */
export function iconSvg(p) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120">
  <!-- tiny app-icon mark — static, opaque variant of logo.svg (the meta-agent
       node with orbiting tinys). Single source for the iOS AppIcon (1024),
       the PWA icons (512/192) and Play's required hi-res icon (512, rendered
       by gen-store-graphics.mjs). Geometry sits inside the maskable safe zone
       (reach 46/120 = 38% < 40%), so the same render survives every mask.
       GENERATED by scripts/gen-logo.mjs — edit the template there. -->
${defs(p, 'i')}
  <rect width="120" height="120" fill="${p.bg}"/>
  <circle cx="60" cy="60" r="34" fill="url(#i-glow)"/>
  <g>
${orbitDots(p)}
  </g>
  <g>
${counterDots(p)}
  </g>
  <circle cx="60" cy="60" r="15" fill="url(#i-core)"/>
</svg>
`
}

/** Android adaptive-icon foreground. The 108dp viewport masks to a center
 *  circle of r33 (the 66dp safe zone), so the mark shrinks by 33/46 relative
 *  to the icon render — every launcher shape keeps all five orbit dots.
 *  VectorDrawable has no radial-gradient-with-3-stops shorthand pain: aapt
 *  inflates the <gradient> at build time (minSdk 26 > the API-24 floor). */
export function androidForegroundXml(p) {
  const s = 33 / 46                       // safe-zone scale
  const m = (v) => +(54 + (v - 60) * s).toFixed(2)  // map 120-box coord → 108dp box
  const r = (v) => +(v * s).toFixed(2)
  const circle = (cx, cy, rad) => `M${m(cx)},${m(cy)}m-${r(rad)},0a${r(rad)},${r(rad)} 0,1 1,${r(rad) * 2},0a${r(rad)},${r(rad)} 0,1 1,-${r(rad) * 2},0`
  const dot = (cx, cy, rad, color, alpha = '1') => `    <path android:fillColor="${color}" android:fillAlpha="${alpha}"
        android:pathData="${circle(cx, cy, rad)}" />`
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- tiny — the meta-agent node with orbiting tinys, from public/logo.svg.
     GENERATED by scripts/gen-logo.mjs — regenerate, don't hand-edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- halo -->
    <path android:pathData="${circle(60, 60, 34)}">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial"
                android:centerX="54" android:centerY="54" android:gradientRadius="${r(34)}">
                <item android:offset="0" android:color="#D9${p.accent.slice(1)}" />
                <item android:offset="0.55" android:color="#38${p.accent.slice(1)}" />
                <item android:offset="1" android:color="#00${p.accent.slice(1)}" />
            </gradient>
        </aapt:attr>
    </path>
    <!-- orbiting tinys (frozen at the logo's rest frame) -->
${dot(60, 18, 4, p.accent)}
${dot(102, 60, 3, p.accent, '0.8')}
${dot(60, 102, 3.4, p.lightDot)}
${dot(24, 44, 2.6, p.accent, '0.7')}
${dot(96, 88, 2.6, p.accent, '0.7')}
    <!-- core -->
    <path android:pathData="${circle(60, 60, 15)}">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial"
                android:centerX="54" android:centerY="${m(55)}" android:gradientRadius="${r(16.5)}">
                <item android:offset="0" android:color="${p.highlight}" />
                <item android:offset="0.45" android:color="${p.accent}" />
                <item android:offset="1" android:color="${p.shade}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
`
}

// ── main ────────────────────────────────────────────────────────────────────
const main = () => {
  const accent = process.argv[2] || '#00FF88'
  const p = derivePalette(accent)
  const tinted = derivePalette('#cccccc') // grayscale: iOS 18 tints it itself

  const w = (rel, content) => { writeFileSync(join(ROOT, rel), content); console.log('  wrote', rel) }
  w('public/logo.svg', animatedSvg(p))
  w('public/icon-source.svg', iconSvg(p))
  w('android/app/src/main/res/drawable/ic_launcher_foreground.xml', androidForegroundXml(p))
  w('android/wear/src/main/res/drawable/ic_launcher_foreground.xml', androidForegroundXml(p))

  const tmp = mkdtempSync(join(tmpdir(), 'tiny-logo-'))
  try {
    const iconPath = join(tmp, 'icon.svg')
    const tintedPath = join(tmp, 'tinted.svg')
    writeFileSync(iconPath, iconSvg(p))
    writeFileSync(tintedPath, iconSvg(tinted))
    const png = (src, size, rel) => {
      execFileSync('rsvg-convert', ['-w', String(size), '-h', String(size), src, '-o', join(ROOT, rel)])
      console.log('  wrote', rel)
    }
    png(iconPath, 192, 'public/icon-192.png')
    png(iconPath, 512, 'public/icon-512.png')
    png(iconPath, 512, 'public/icon-maskable-512.png')
    png(iconPath, 512, 'app/icon.png')
    png(iconPath, 1024, 'ios/Tiny/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png')
    png(iconPath, 1024, 'ios/Tiny/Assets.xcassets/AppIcon.appiconset/AppIcon-1024-dark.png')
    png(tintedPath, 1024, 'ios/Tiny/Assets.xcassets/AppIcon.appiconset/AppIcon-1024-tinted.png')
    png(iconPath, 1024, 'ios/TinyWatch/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png')
  } finally {
    rmSync(tmp, { recursive: true, force: true })
  }
  console.log(`done — accent ${accent} (highlight ${p.highlight}, shade ${p.shade}, bg ${p.bg})`)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
